#+BEGIN_COMMENT
.. title: README
.. hidetitle: True
.. slug: index
.. date: 2017-04-16 23:43:22 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: toc:nil



You are at a right place if you are looking for:

1. Nepali scientists working somewhere in the world in your field of interest ([[../Nepali-scholars/][link]]),

2. Nepali research institutes doing great works in the field of your interest ([[../Nepali-research-institutions][link]]),

3. Explore Nepali science, technology and innovation industry, ([[../Nepali-innovation-industry/][link]])

4. Find out journals and conferences in Nepal ([[../Nepali-journals-conferences/][link]]).

Please contribute to expand and keep this resource up to date by creating an issue or pull request [[https://github.com/AbhinavNepal/Science-innovation-Nepal][at github]] for any addition/correction.
Please let me know if:

1. there is someone {(even you :)} who is not in the list but should be,

2. any information present here is wrong, or not updated,

3. you have (a) suggestion(s) on how to expand or add other different kinds of information.

I hope these resources are useful for anyone interested in doing science and innovation related works in/for Nepal.

*Copyright and usage:*
All the information in this website are collected from public websites such as google scholar, researchgate, personal/academic websites of the related people.
The collective information produced as a result of the resources in this website, and any new information/data that uses these resources should always be open access and freely available.
