Useful resources that can help anyone interested in doing science and innovation related works in/for Nepal.

The website is [[http://bishesh.github.io/Science-innovation-Nepal/][here]]

You can also contribute to the repository by creating an issue or asking for a pull request when:

1. there is someone {(even you :)} who is not in the list but should be,

2. any information present here is wrong, or not updated,

3. you have (a) suggestion(s) on how to expand or add other different kinds of information.

* Lists maintained so far
- Page with a list of Nepali scholars around the world.
- Page with a list of research institutions in Nepal (those who have a proper list of publications in their website)
- Page with a list of innovative and emerging tech-related companies in Nepal
- Page with a list of plagiarism incidences in Nepal.

* Wish lists
- Page with a list of grants, fellowship available for scientists world-wide
- *What ideas do you have ?*

* Long term vision
1. A central place for Nepali scientific community to discuss ideas implement them to leap forward Nepal into the modern world order of science and technology.
2. Building a community that works as a movement to help:
   - identify major problems in Government's laws and policies regarding higher education and research in Nepal
   - develop a working document that could address the issues with existing laws and policies of the Government, and of the major Universities.

We cannot have major improvements without transforming and strengthening the existing state universities and research institutions.
Thus, we can try to identify major problems, propose solutions, and appeal civil society and opinion makers to exert pressure on the parliament (and the major political parties) to make reforms.

** Example of such a work: Proposing improved laws for meritocracy in Universities:

- Identify Government and University laws that govern the promotion of academicians/researchers in Universities and Research institutes.
- With help from experts, propose concrete amendments to any laws and policies that are hindering the transformation of these institutions.
  E.g. scientific and measurable merit based promotion policy
- Exert pressure on Government to implement a system of transparency where anyone in the public can easily access relevant data of any academician (under the legal provisions of access to information) : the promotion dates of any academician, the committee members that decided on the selection/promotion, the list of publications and other relevant merits provided by the concerned person at the time of his promotion.


* Will always be a non-political community
In a highly politicized society like ours, there is a high risk of the community like ours to fall into a trap of getting biased or closer to a particular political party.
We should develop concrete guidelines to avoid such a (tragic) possibility.
This should be a community of scholars with academic and professional integrity.
All forms of prejudice should be tackled wisely.



