#+BEGIN_COMMENT
.. title: Nepali Research Institutions
.. slug: Nepali-research-institutions
.. date: 2017-04-16 23:56:18 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: toc:nil


- A curated list of Nepali research institutions and labs.
- To make into this list, the organization must regularly update their list of contributions in peer-reviewed conferences and journals of "good quality".
- *Reports written by NGOs* without any corresponding publications in a peer-review journals/conferences do not count!

We know, "good quality" is difficult to measure, this is a *TODO*.
We hope that we can come up with some metrics for this {(suggestions are welcome :)}.


#+TOC: headlines 1

* Encompassing broader domains

1. [[http://www.kias.org.np/][Kathmandu Institute of Applied Sciences]]
  - Currently seems to be working on analytical chemistry and conservation science.

* Environmental and Agricultural Sciences

1. [[https://www.astajardcnepal.org][Asta-Ja Research and Development Center]]
   - *Need to put peer-reviewed publications in conferences and journals at ONE place*!!
   - Agricultural, natural resources, environmental and other research and developmental projects.
  
2. *TODO* [[www.icimod.org/][ICIMOD]]
   - Need to see where they put their publications!!
   - "Develop an economically and environmentally sound mountain ecosystem to improve the living standards of mountain populations and to sustain vital ecosystem services for the billions of people living downstream now, and for the future."

* Life Sciences, Wildlife and Public Health

1. [[http://www.chdsnepal.org/][Center for Health and Disease Studies Nepal]]
   - Established very recently; waiting to see their publications
 
2. [[http://www.cmdn.org.np/][Center for Modelcular Dynamics Nepal]]
   - Public health, biotechnology and wildlife research

3. [[https://www.tropicalmedicine.ox.ac.uk/nepal][Oxford University Clinical Research Unit - Nepal]]
   - Hosted by Patan Hospital
   - Major focus on enteric fever (Typhoid and Paratyphoid) and other causes of febrile illness including typhus, infections of the central nervous system and Hepatitis E.
   - Future plans to include viral causes of pneumonia, TB, emerging illnesses and other public health priorities in Nepal.
   - High altitiude sickness in Nepalese and travelers.

4. [[http://ribb.org.np/][Research Institute for Bioscience and Biotechnology]]
   - *They must make their publications easily available !!*
   - Focus areas:
     - Medicinal Plant Research
     - Pharmaceutical Research
     - Food Science Research
     - Strain Culture Center

5. [[http://kribs.org.np/][Kathmandu Research Institute for Biological Sciences]]
   - Established in 2017, starting focus: Infection and immunology; natural products.
   - Objective: "research and development of tools and techniques with an aim to enable the study inside biological sciences".

* Material Science, Nanomaterials and Biomaterials

1. [[http://www.nepalpolymer.org/][Nepal Polymer]]
  - Says that website under construction!
    Hope to see list of publications soon!!
