#+BEGIN_COMMENT
.. title: Kill-plagiarism
.. slug: Kill-plagiarism
.. date: 2017-10-13 16:54:18 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: toc:nil

Plagiarism has been a major problem in Nepal.
Let us add the incidents of plagiarism with as much proof as possible (original + plagiarised materials, retraction decisions, correspondences, etc.) that we can find.

If you are aware of any such incidences that is not listed here, please let us know by either:

- Adding the details and creating a pull request or,
- commenting [[github-link][here]] (AKA creating an issue).

We hope this page will help us realize the magnitude of the plagiarism problem in higher education and research in Nepal.
The collected data should also help understand the nature and type of its prevalence in different institutions.
We also want to use this platform to raise awareness about plagiarism and discourage people from doing it.

#+TOC: headlines 1

* Hall of Shame

This section accounts the incidences of plagiarism from well known personalities or those who have held high positions in academia or public institutions.

1. 

* Journal papers

1. http://www.myrepublica.com/news/28976/

* Conference papers

* Books

* PhD Theses

* Masters Theses


