#+BEGIN_COMMENT
.. title: Nepali Innovation Industry
.. slug: Nepali-innovation-industry
.. date: 2017-04-16 23:56:18 UTC+01:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: toc:nil

# A curated list of innovative companies and organizations in Nepal.

I do not intend to put outsourcing companies in this list.
The list will have companies that have some of the following traits:

1. Established in Nepal

2. disruptive innovation

3. potential of having a big positive social impact

4. collecting and making data available that could facilitate research

5. doing research or collaborating with research institutions to build new world knowledge

#+TOC: headlines 1

* Education and Technology

- [[http://www.karkhana.asia/][Karkhana]]
  - "Teachers, Tinkers, Experimenters!"
  - "Catalyze an ecosystem that permits the kids they teach to do the things they were unable to do – create innovative solutions to local problems, and make a living while doing it."

* Machine Learning and Artificial Intelligence

** Natural Language and Speech Processing 

- [[http://integratedict.com.np/website/index.php][IntegratedICT]]
  - Applying the latest developments in AI to develop novel solutions to challenging problems.
    Team of computer scientists and software Engineers and founded in 2012.

* Society, Development and Open Data

- [[http://www.kathmandulivinglabs.org/][Kathmandu Living Labs (KLL)]]
  - "A civic tech group striving to co-create digital tools and information infrastructure so that government, nonprofits and businesses can use 21st century technology to provide everyday citizens the best services."
  - Has worked mostly in collecting and visualizing mapping data useful for various socio-economic aspects. 

- [[http://nalibeli.org/][Nalibeli]] and [[http://galligalli.org/][Galligalli]]
  - "Make people's lives easier by providing information on processes – formal and informal – for accessing government services."
  - All Government rules and regulations for public service in one single place with wikipedia style collaboration strategy.

- [[http://opennepal.net/][OpenNepal]]
  - "A knowledge hub and a learning space for organizations and people that produce, share and use data for development"
  - "Open Nepal exists to improve how data for development is produced, shared and used in Nepal by supporting a community of civil society groups, media, private sector, government and academia to share data lessons, experiences, expertise and ideas."

